version: 2

multi-ecosystem-groups:
  pdfding:
    schedule:
      interval: "cron"
      # every second sunday
      cronjob: "0 8 * * sun%2"

updates:
  - package-ecosystem: "pip"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "pdfding"
  - package-ecosystem: "npm"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "pdfding"
  - package-ecosystem: "docker"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "pdfding"
    ignore:
      - dependency-name: "python"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]
