version: '3'

services:
  pdfding:
    container_name: pdfding
    image: mrmn/pdfding:latest
    volumes:
      - media:/home/nonroot/pdfding/media
      # If you use selinux it might be necessary to add the :Z after the volume
      # - media:/home/nonroot/pdfding/media:Z
    environment:
      - DEFAULT_THEME=${DEFAULT_THEME:-dark}
      - DEFAULT_THEME_COLOR=${DEFAULT_THEME_COLOR:-blue}
      # use a long random secret
      - SECRET_KEY=${SECRET_KEY:-some_secret}
      # the domain where you want to access PdfDing, e.g. pdfding.com
      - HOST_NAME=${HOST_NAME:-127.0.0.1}
      - DATABASE_TYPE=${DATABASE_TYPE:-POSTGRES}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pdfding}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      # In production set the following values to True
      - CSRF_COOKIE_SECURE=${CSRF_COOKIE_SECURE:-'FALSE'}
      - SESSION_COOKIE_SECURE=${SESSION_COOKIE_SECURE:-'FALSE'}
    ports:
      - "8000:8000"

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=pdfding
      - POSTGRES_USER=pdfding
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pdfding}
      - POSTGRES_PORT=5432

volumes:
  media:
  postgres_data:
